server:
  port: 7090
  servlet:
    session:
      timeout: PT12H

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  messages:
    basename: messages,i18n/messages
  datasource:
    url: jdbc:mysql://192.168.1.21:3306/irdb?useSSL=false&characterEncoding=UTF-8
    username: irsoft
    password: irsoft
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 5
    max-wait: 10000
    min-idle: 2
    initial-size: 3
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)

security:
  authn:
    data:
      password-encoder:
        type: bss

