server:
  port: 7092

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://authserver:7090/oauth2/keys